.TH DWM-SESSION 1 "dwm-session" "User Commands"
.SH NAME
dwm-session \- start a dwm-based X session
.SH SYNOPSIS
.B dwm-session
.SH DESCRIPTION
The
.B dwm-session
script starts an X session using the
.B dwm
window manager. It starts
.BR xcompmgr (1)
as a compositor and set a desktop wallpaper using
.BR feh (1).
System X session startup script used by
.BR startx (1).
.SH SEE ALSO
.BR dwm (1),
.BR xcompmgr (1),
.BR feh (1),
.BR startx (1),
.BR Xsession (5)
.SH AUTHOR
Written by Marco Trevisiol <marco@trevisiol.casa>.

